# Generated by Django 6.0 on 2026-01-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interacciones', '0002_preguntasfrecuentes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valoracionreceta',
            options={},
        ),
        migrations.RemoveField(
            model_name='valoracionreceta',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='valoracionreceta',
            name='fecha_creacion',
        ),
    ]
