# Generated by Django 6.0.2 on 2026-02-13 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_chef_usuario_alter_rol_nombre_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_chef', to=settings.AUTH_USER_MODEL),
        ),
    ]
