# Generated by Django 6.0.4 on 2026-05-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interacciones', '0002_valoracionreceta_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracionreceta',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valoracionshowcooking',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
