# Generated by Django 6.0 on 2026-01-22 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_receta',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='categoria_showcooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ingredientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('imagen', models.ImageField(default='recetas/default.jpg', upload_to='recetas/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ingredientes', models.TextField(null=True)),
                ('instrucciones', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada')], default='borrador', max_length=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooking.categoria_receta')),
            ],
        ),
        migrations.CreateModel(
            name='ingredientes_receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField()),
                ('id_ingrediente', models.ForeignKey(default='AA', on_delete=django.db.models.deletion.SET_DEFAULT, to='cooking.ingredientes')),
                ('id_Receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking.receta')),
            ],
        ),
        migrations.CreateModel(
            name='Chef_Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chef', models.ForeignKey(default='AA', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('id_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking.receta')),
            ],
        ),
        migrations.CreateModel(
            name='Showcooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(default='showcookings/default.jpg', upload_to='imagenes/')),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('url_youtube', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=10)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('intermedio', 'Intermedio'), ('dificil', 'Difícil')], default='intermedio', max_length=15)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking.categoria_showcooking')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='showcooking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='cooking.showcooking'),
        ),
        migrations.CreateModel(
            name='Chef_ShowCooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chef', models.ForeignKey(default='Vacio', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('id_showcooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking.showcooking')),
            ],
        ),
    ]
