# Generated by Django 6.0.4 on 2026-05-12 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0007_alter_showcooking_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='nombre',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AddField(
            model_name='ingredientes_receta',
            name='bloque_preparacion',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='ingredientes_receta',
            name='cantidad',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='ingredientes_receta',
            name='id_ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_asociadas', to='cooking.ingredientes'),
        ),
        migrations.AlterField(
            model_name='ingredientes_receta',
            name='id_Receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_items', to='cooking.receta'),
        ),
    ]
