# Generated by Django 6.0.5 on 2026-05-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0008_receta_ingredientes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientes',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='ingredientes_receta',
            options={'ordering': ['id']},
        ),
    ]
