# Generated by Django 6.0.4 on 2026-05-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0011_drop_stale_receta_ingredientes_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showcooking',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
