# Generated by Django 6.0 on 2026-01-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_usuario_options_usuario_biografia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Registrado', 'Registrado'), ('cocinero', 'Cocinero'), ('admin', 'Administrador'), ('editor_de_videos', 'Editor de Videos')], default='Registrado', max_length=20),
        ),
    ]
