# Generated by Django 6.0 on 2026-01-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_usuario_id_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Registrado', 'Registrado'), ('cocinero', 'Cocinero'), ('admin', 'Administrador')], default='Registrado', max_length=20),
        ),
    ]
