# Generated by Django 6.0 on 2026-01-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_showcooking_categoria_showcooking_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcooking',
            name='url_youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
