# Generated by Django 6.0 on 2026-01-06 19:19

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_alter_showcooking_url_youtube'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='valoracion_promedio',
            field=models.FloatField(default=0.0, help_text='Valoración promedio calculada automáticamente', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='showcooking',
            name='cocineros',
            field=models.ManyToManyField(related_name='showcookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
