# Generated by Django 6.0 on 2026-01-11 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_receta_valoracion_promedio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='valoracion_promedio',
        ),
        migrations.RemoveField(
            model_name='showcooking',
            name='cocineros',
        ),
        migrations.AddField(
            model_name='receta',
            name='tematica',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.RemoveField(
            model_name='receta',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='receta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='showcooking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ParticipacionShowcooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_showcooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='cooking.showcooking')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_showcooking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='categoria',
            field=models.CharField(choices=[('Tematica', 'Temática'), ('Por autor', 'Por Autor'), ('Saludable', 'Saludable'), ('Interactivo', 'Interactivo')], default='Tematica', max_length=100),
        ),
    ]
