# Generated by Django 6.0 on 2026-01-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0005_remove_receta_valoracion_promedio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcooking',
            name='imagen',
            field=models.ImageField(default='showcookings/default.jpg', upload_to='showcookings/'),
        ),
        migrations.AlterField(
            model_name='showcooking',
            name='categoria',
            field=models.CharField(default='General', max_length=10),
        ),
        migrations.AlterField(
            model_name='showcooking',
            name='titulo',
            field=models.CharField(max_length=20),
        ),
    ]
