# Generated by Django 6.0 on 2026-01-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0006_showcooking_imagen_alter_showcooking_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcooking',
            name='imagen',
            field=models.ImageField(default='showcookings/default.jpg', upload_to='imagenes/'),
        ),
    ]
