# Generated by Django 6.0 on 2026-01-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0007_alter_showcooking_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(default='recetas/default.jpg', upload_to='recetas/'),
        ),
    ]
