# Generated by Django 6.0 on 2026-01-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0008_receta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=models.TextField(null=True),
        ),
    ]
